[package]
name = "blake"
version = "0.1.0"
authors = ["Jonathan Lange <jml@mumak.net>"]
edition = "2018"

[dependencies]
clap = "2.33"
chrono = "0.4"
comrak = "0.6"
fs_extra = "1.1"
lazy_static = "1.3"
tera = "0.11"
